// packages/client/src/components/sheets/pf2e/plan/ABCCard.svelte
<script lang="ts">
  /**
   * ABCCard.svelte — Ancestry/Heritage/Background/Class card at the top of
   * the Plan column. Green check when filled, uppercase type-label, chosen
   * name, optional sub-line (e.g. the Magus's Hybrid Study pick).
   *
   * Ports the design contract's `ABCCard`
   * (.fusion-build/r10-design/claude-design/components/plan/ABCCard.jsx).
   * Clicking an unfilled card (or an editable filled one) opens the matching
   * compendium picker — the caller decides via `onClick`.
   */

  interface Props {
    typeLabel: string;
    name?: string | undefined;
    subLine?: string | undefined;
    filled: boolean;
    editable: boolean;
    onClick: () => void;
  }

  let { typeLabel, name, subLine, filled, editable, onClick }: Props = $props();
</script>

<button
  type="button"
  class="abc-card"
  class:abc-card--clickable={editable}
  disabled={!editable}
  onclick={onClick}
>
  <span class="abc-card__badge" class:abc-card__badge--done={filled} aria-hidden="true">
    {#if filled}&#10003;{/if}
  </span>
  <span class="abc-card__body">
    <span class="abc-card__label">{typeLabel}</span>
    <span class="abc-card__name">{name ?? "—"}</span>
    {#if subLine}<span class="abc-card__subline">{subLine}</span>{/if}
  </span>
</button>

<style>
  .abc-card {
    background: var(--fusion-surface-alt);
    border: 1px solid var(--fusion-border);
    border-radius: var(--fusion-radius);
    padding: 10px 12px;
    display: flex;
    align-items: center;
    gap: 10px;
    width: 100%;
    text-align: left;
    font-family: var(--fusion-font);
    cursor: default;
  }

  .abc-card--clickable {
    cursor: pointer;
    transition: border-color 0.12s;
  }

  .abc-card--clickable:hover,
  .abc-card--clickable:focus-visible {
    border-color: var(--fusion-accent);
  }

  .abc-card__badge {
    width: 18px;
    height: 18px;
    border-radius: 50%;
    background: transparent;
    border: 1px dashed var(--fusion-border);
    color: var(--fusion-success);
    display: flex;
    align-items: center;
    justify-content: center;
    font-size: 11px;
    font-weight: 700;
    flex-shrink: 0;
  }

  .abc-card__badge--done {
    background: var(--fusion-success-dim);
    border: none;
  }

  .abc-card__body {
    flex: 1;
    min-width: 0;
    display: flex;
    flex-direction: column;
  }

  .abc-card__label {
    font-size: 10px;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    color: var(--fusion-text-subtle);
  }

  .abc-card__name {
    font-size: 13px;
    font-weight: 600;
    color: var(--fusion-text);
  }

  .abc-card__subline {
    font-size: 11px;
    color: var(--fusion-text-muted);
    margin-top: 2px;
  }
</style>

// .fusion-build/r10-design/claude-design/components/plan/ABCCard.jsx
import React from "react";

/**
 * Ancestry/Heritage/Background/Class card in the plan column. A green check,
 * an uppercase type-label, the chosen name, and an optional sub-line.
 */
export function ABCCard({ typeLabel, name, subLine, done = true, style }) {
  return (
    <div
      style={{
        background: "var(--fusion-surface-alt)",
        border: "1px solid var(--fusion-border)",
        borderRadius: "var(--fusion-radius)",
        padding: "10px 12px",
        display: "flex",
        alignItems: "center",
        gap: "10px",
        ...style,
      }}
    >
      <div
        style={{
          width: 18,
          height: 18,
          borderRadius: "50%",
          background: done ? "var(--fusion-success-dim)" : "transparent",
          border: done ? "none" : "1px dashed var(--fusion-border)",
          color: "var(--fusion-success)",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          fontSize: "11px",
          fontWeight: 700,
          flexShrink: 0,
        }}
      >
        {done ? "\u2713" : ""}
      </div>
      <div style={{ flex: 1, minWidth: 0 }}>
        <div style={{ fontSize: "10px", textTransform: "uppercase", letterSpacing: "0.04em", color: "var(--fusion-text-subtle)" }}>
          {typeLabel}
        </div>
        <div style={{ fontSize: "13px", fontWeight: 600, color: "var(--fusion-text)" }}>{name}</div>
        {subLine && <div style={{ fontSize: "11px", color: "var(--fusion-text-muted)", marginTop: "2px" }}>{subLine}</div>}
      </div>
    </div>
  );
}
